{% set version = "0.4.0" %}

package:
  name: pygcgopt
  version: {{ version }}

source:
  url: https://github.com/scipopt/PyGCGOpt/archive/v{{ version }}.tar.gz
  sha256: 99978a6a313e12028169e9c6783d7d14855a307fcce0003dd869abe2656f2362

build:
  number: 0
  script: '"${PYTHON}" -m pip install .'  # [unix]
  script: '"%PYTHON%"  -m pip install .'  # [win]
  script_env:
    - GCGOPTDIR="${PREFIX}"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - scip
    - gcg
    - python
    - pip
    - cython >=3
    - pyscipopt >=5.2.1
  run:
    - python
    - pyscipopt >=5.2.1

test:
  imports:
    - pygcgopt
    - pygcgopt.gcg
  commands:
    - python -c 'import pygcgopt.gcg; pygcgopt.gcg.Model()'

about:
  home: https://github.com/scipopt/PyGCGOpt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface and modeling environment for GCG
  doc_url: https://scipopt.github.io/PyGCGOpt/

extra:
  recipe-maintainers:
    - jurgen-lentz
